# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpacket.proto\x12\x10network_analyzer\"\xf1\x04\n\x06Packet\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\x0e\n\x06src_ip\x18\x03 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x04 \x01(\t\x12\x10\n\x08protocol\x18\x05 \x01(\t\x12\x0e\n\x06length\x18\x06 \x01(\x05\x12\x10\n\x08src_port\x18\x07 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x08 \x01(\x05\x12\x11\n\ttcp_flags\x18\t \x01(\t\x12\x0f\n\x07tcp_syn\x18\n \x01(\x08\x12\x0f\n\x07tcp_ack\x18\x0b \x01(\x08\x12\x0f\n\x07tcp_fin\x18\x0c \x01(\x08\x12\x0f\n\x07tcp_rst\x18\r \x01(\x08\x12\x0f\n\x07tcp_psh\x18\x0e \x01(\x08\x12\x0b\n\x03seq\x18\x0f \x01(\x03\x12\x0f\n\x07\x61\x63k_num\x18\x10 \x01(\x03\x12\x11\n\ticmp_type\x18\x11 \x01(\x05\x12\x11\n\ticmp_code\x18\x12 \x01(\x05\x12\x0e\n\x06\x61rp_op\x18\x13 \x01(\x05\x12\x10\n\x08\x61rp_psrc\x18\x14 \x01(\t\x12\x10\n\x08\x61rp_pdst\x18\x15 \x01(\t\x12\x11\n\tarp_hwsrc\x18\x16 \x01(\t\x12\x11\n\tarp_hwdst\x18\x17 \x01(\t\x12\x11\n\tdns_query\x18\x18 \x01(\x08\x12\x11\n\tdns_qname\x18\x19 \x01(\t\x12\x11\n\tdns_qtype\x18\x1a \x01(\x05\x12\x14\n\x0c\x64ns_response\x18\x1b \x01(\x08\x12\x18\n\x10\x64ns_answer_count\x18\x1c \x01(\x05\x12\x17\n\x0f\x64ns_answer_size\x18\x1d \x01(\x05\x12\x13\n\x0bhttp_method\x18\x1e \x01(\t\x12\x11\n\thttp_path\x18\x1f \x01(\t\x12\x18\n\x10http_status_code\x18  \x01(\t\x12\x11\n\thttp_host\x18! \x01(\t\"Q\n\rIngestSummary\x12\x16\n\x0ereceived_count\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x18\n\x10server_timestamp\x18\x03 \x01(\x01\x32_\n\rIngestService\x12N\n\rStreamPackets\x12\x18.network_analyzer.Packet\x1a\x1f.network_analyzer.IngestSummary\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKET']._serialized_start=35
  _globals['_PACKET']._serialized_end=660
  _globals['_INGESTSUMMARY']._serialized_start=662
  _globals['_INGESTSUMMARY']._serialized_end=743
  _globals['_INGESTSERVICE']._serialized_start=745
  _globals['_INGESTSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
